services:
  - type: web
    name: 20-web-career-navigator
    env: static
    buildCommand: npm run build
    publishDirectory: dist
    headers:
      - source: /**
        headers:
          - Cache-Control: public, max-age=31536000, immutable
