import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Search, ChevronRight, Download, Layers, Zap, BarChart, Target, Check, ChevronLeft } from 'lucide-react';
import { useTechStore } from '@/stores/techStore';
import { ROADMAPS } from '@/data/roadmaps';
import type { TechCategory } from '@/types/tech';

export function RoadmapExplorer() {
  const {
    searchQuery,
    setSearchQuery,
    activeCategory,
    setActiveCategory,
    selectedTechId,
    setSelectedTechId,
    completedMilestoneIds,
    toggleMilestoneCompleted,
  } = useTechStore();

  const [mobileView, setMobileView] = useState<'list' | 'detail'>('list');

  const categories: { id: TechCategory | 'all'; label: string }[] = [
    { id: 'all', label: 'All Tech' },
    { id: 'web', label: 'Web' },
    { id: 'ai', label: 'AI/ML' },
    { id: 'cloud', label: 'Cloud' },
    { id: 'data', label: 'Data' },
    { id: 'security', label: 'Security' },
  ];

  const filteredRoadmaps = ROADMAPS.filter(tech => {
    const matchesSearch =
      tech.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      tech.description.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesCategory = activeCategory === 'all' || tech.category === activeCategory;
    return matchesSearch && matchesCategory;
  });

  // Automatically select first item on desktop load if nothing is selected
  useEffect(() => {
    if (!selectedTechId && filteredRoadmaps.length > 0) {
      setSelectedTechId(filteredRoadmaps[0].id);
    }
  }, [filteredRoadmaps, selectedTechId, setSelectedTechId]);

  const selectedTech = ROADMAPS.find(t => t.id === selectedTechId);

  const handleExport = (tech: typeof ROADMAPS[0]) => {
    const mdContent = `# ${tech.name} Roadmap\n\n${tech.description}\n\n## Milestones\n${tech.milestones
      .map(
        ms =>
          `- [${completedMilestoneIds.includes(ms.id) ? 'x' : ' '}] ${ms.year} - ${ms.title}: ${
            ms.description
          }`
      )
      .join('\n')}\n\n---\nGenerated by MK PathForge by Qazi Musharof`;

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `mk-pathforge-${tech.id}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const completedCount = selectedTech
    ? selectedTech.milestones.filter(ms => completedMilestoneIds.includes(ms.id)).length
    : 0;
  const totalCount = selectedTech ? selectedTech.milestones.length : 0;
  const percent = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
      {/* Left side: Roadmap Navigator */}
      <div
        className={clsx(
          'lg:col-span-4 space-y-6',
          mobileView === 'detail' ? 'hidden lg:block' : 'block'
        )}
      >
        <div className="flex flex-col gap-4">
          {/* Search box */}
          <div className="relative w-full">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
            <input
              type="text"
              value={searchQuery}
              onChange={e => setSearchQuery(e.target.value)}
              placeholder="Search technologies..."
              className="w-full glass rounded-2xl pl-12 pr-4 py-3.5 outline-none focus:ring-2 focus:ring-tech-primary/20 transition-all font-medium dark:text-white"
            />
          </div>

          {/* Categories select pills */}
          <div className="flex gap-2 p-1.5 bg-white/30 dark:bg-slate-900/50 backdrop-blur-xl border border-white/20 dark:border-slate-800/40 rounded-2xl overflow-x-auto no-scrollbar">
            {categories.map(cat => (
              <button
                key={cat.id}
                onClick={() => setActiveCategory(cat.id)}
                className={clsx(
                  'px-4 py-2 rounded-xl text-xs font-black uppercase tracking-wider whitespace-nowrap transition-all',
                  activeCategory === cat.id
                    ? 'bg-tech-primary text-white shadow-lg shadow-tech-primary/20'
                    : 'text-slate-500 hover:text-slate-700 dark:hover:text-slate-300'
                )}
              >
                {cat.label}
              </button>
            ))}
          </div>
        </div>

        {/* Tech list */}
        <div className="space-y-4 max-h-[calc(100vh-22rem)] overflow-y-auto pr-2 custom-scrollbar">
          {filteredRoadmaps.map((tech, idx) => {
            const isSelected = selectedTechId === tech.id;
            const techCompleted = tech.milestones.filter(ms => completedMilestoneIds.includes(ms.id)).length;
            const techTotal = tech.milestones.length;
            const techPercent = techTotal > 0 ? Math.round((techCompleted / techTotal) * 100) : 0;

            return (
              <motion.div
                key={tech.id}
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.03 }}
                onClick={() => {
                  setSelectedTechId(tech.id);
                  setMobileView('detail');
                }}
                className={clsx(
                  'group p-5 rounded-3xl cursor-pointer transition-all border flex items-center justify-between',
                  isSelected
                    ? 'border-tech-primary/50 bg-white/50 dark:bg-slate-900/50 shadow-xl'
                    : 'glass hover:border-tech-primary/30'
                )}
              >
                <div className="flex items-center gap-4 min-w-0">
                  <div className="text-3xl p-2 bg-slate-100/50 dark:bg-slate-800/50 rounded-2xl">{tech.icon}</div>
                  <div className="min-w-0">
                    <h3 className="font-display font-black text-base truncate dark:text-white">{tech.name}</h3>
                    {techPercent > 0 ? (
                      <p className="text-xs text-tech-secondary font-bold">
                        {techPercent}% Completed ({techCompleted}/{techTotal})
                      </p>
                    ) : (
                      <p className="text-xs text-slate-400 truncate">{tech.description}</p>
                    )}
                  </div>
                </div>
                <ChevronRight
                  className={clsx(
                    'w-5 h-5 text-slate-300 transition-colors',
                    isSelected ? 'text-tech-primary' : 'group-hover:text-tech-primary'
                  )}
                />
              </motion.div>
            );
          })}

          {filteredRoadmaps.length === 0 && (
            <div className="text-center py-16 glass rounded-3xl">
              <Layers className="w-12 h-12 text-slate-300 dark:text-slate-700 mx-auto mb-3" />
              <p className="text-sm font-bold text-slate-400">No technologies found</p>
              <button
                onClick={() => {
                  setSearchQuery('');
                  setActiveCategory('all');
                }}
                className="text-tech-primary font-bold text-xs mt-1 underline"
              >
                Clear filters
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Right side: Interactive Roadmap Tree Detail Panel */}
      <div className={clsx('lg:col-span-8', mobileView === 'list' ? 'hidden lg:block' : 'block')}>
        <AnimatePresence mode="wait">
          {selectedTech ? (
            <motion.div
              key={selectedTech.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="glass p-6 md:p-8 rounded-[2.5rem] shadow-xl space-y-6 relative overflow-hidden"
            >
              {/* Card visual blob header */}
              <div
                className={`absolute top-0 right-0 w-48 h-48 bg-gradient-to-br ${selectedTech.color} opacity-5 blur-3xl`}
              />

              {/* Title Header area */}
              <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pb-6 border-b border-slate-200/50 dark:border-slate-800/50">
                <div className="flex items-center gap-4">
                  {/* Mobile Back button */}
                  <button
                    onClick={() => setMobileView('list')}
                    className="lg:hidden p-2.5 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-500 hover:text-tech-primary transition-all"
                    aria-label="Back to tech list"
                  >
                    <ChevronLeft size={18} />
                  </button>
                  <div className="text-5xl p-3 bg-slate-100/30 dark:bg-slate-900/30 rounded-2xl backdrop-blur-md">
                    {selectedTech.icon}
                  </div>
                  <div>
                    <h2 className="text-3xl font-display font-black tracking-tight dark:text-white">
                      {selectedTech.name}
                    </h2>
                    <p className="text-slate-400 text-xs font-bold uppercase tracking-wider mt-0.5">
                      {selectedTech.category} Roadmap
                    </p>
                  </div>
                </div>

                <button
                  onClick={() => handleExport(selectedTech)}
                  className="w-full sm:w-auto px-5 py-3 bg-tech-primary text-white font-black text-xs uppercase tracking-wider rounded-xl flex items-center justify-center gap-2 hover:scale-[1.03] transition-transform active:scale-95 shadow-lg shadow-tech-primary/10"
                >
                  Export Roadmap <Download size={15} />
                </button>
              </div>

              {/* Stats overview banner */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className="bg-slate-100/30 dark:bg-slate-900/30 p-4 rounded-2xl border border-white/15">
                  <p className="text-[10px] font-black uppercase tracking-widest text-slate-400 mb-1">
                    Market Growth
                  </p>
                  <div className="flex items-center gap-2">
                    <Zap className="text-tech-secondary w-5 h-5" />
                    <p className="text-xl font-black dark:text-white">+{selectedTech.growth}%</p>
                  </div>
                </div>
                <div className="bg-slate-100/30 dark:bg-slate-900/30 p-4 rounded-2xl border border-white/15">
                  <p className="text-[10px] font-black uppercase tracking-widest text-slate-400 mb-1">
                    Job Demand
                  </p>
                  <div className="flex items-center gap-2">
                    <BarChart className="text-tech-accent w-5 h-5" />
                    <p className="text-xl font-black dark:text-white">{selectedTech.demand}%</p>
                  </div>
                </div>
                <div className="bg-slate-100/30 dark:bg-slate-900/30 p-4 rounded-2xl border border-white/15">
                  <p className="text-[10px] font-black uppercase tracking-widest text-slate-400 mb-1">
                    Milestones Complete
                  </p>
                  <p className="text-xl font-black dark:text-white">
                    {completedCount} / {totalCount}
                  </p>
                </div>
              </div>

              {/* Progress Slider bar */}
              <div className="bg-slate-100/30 dark:bg-slate-900/30 p-5 rounded-2xl border border-white/15 space-y-2">
                <div className="flex justify-between text-xs font-black uppercase tracking-wider text-slate-400">
                  <span>Learning Journey Progress</span>
                  <span className="text-tech-primary">{percent}%</span>
                </div>
                <div className="h-2.5 w-full bg-slate-200/50 dark:bg-slate-800/50 rounded-full overflow-hidden">
                  <motion.div
                    initial={{ width: 0 }}
                    animate={{ width: `${percent}%` }}
                    className="h-full bg-gradient-to-r from-tech-primary to-tech-secondary"
                  />
                </div>
              </div>

              {/* Description */}
              <p className="text-slate-500 dark:text-slate-400 text-sm leading-relaxed">
                {selectedTech.description}
              </p>

              {/* Milestone Tree List */}
              <div className="space-y-6 pt-6">
                <h4 className="text-xs font-black uppercase tracking-[0.2em] text-slate-400 flex items-center gap-2">
                  <Target size={15} /> Milestones Timeline
                </h4>

                <div className="relative pl-8 roadmap-line space-y-8">
                  {selectedTech.milestones.map(ms => {
                    const isCompleted = completedMilestoneIds.includes(ms.id);

                    return (
                      <div key={ms.id} className="relative group/node">
                        {/* Interactive Checkbox Circle indicator node */}
                        <button
                          onClick={() => toggleMilestoneCompleted(ms.id)}
                          className={clsx(
                            'absolute -left-[2.35rem] top-1.5 w-6 h-6 rounded-full border-2 z-10 flex items-center justify-center transition-all outline-none cursor-pointer',
                            isCompleted
                              ? 'bg-tech-secondary border-tech-secondary text-white shadow-md shadow-tech-secondary/35 scale-110'
                              : 'bg-white dark:bg-slate-900 border-slate-300 dark:border-slate-700 hover:border-tech-primary hover:scale-105'
                          )}
                          aria-label={isCompleted ? `Mark milestone ${ms.title} as incomplete` : `Mark milestone ${ms.title} as complete`}
                        >
                          {isCompleted ? (
                            <Check size={12} className="stroke-[4]" />
                          ) : (
                            <Check size={12} className="text-tech-primary opacity-0 group-hover/node:opacity-100 transition-opacity stroke-[3]" />
                          )}
                        </button>

                        <div className="glass p-5 rounded-2xl hover:border-tech-primary/30 transition-all space-y-2">
                          <div className="flex items-center justify-between">
                            <span
                              className={clsx(
                                'text-[10px] font-black px-2 py-0.5 rounded-md uppercase tracking-wider',
                                ms.status === 'past'
                                  ? 'bg-emerald-100 text-emerald-600 dark:bg-emerald-900/20'
                                  : ms.status === 'present'
                                    ? 'bg-blue-100 text-blue-600 dark:bg-blue-900/20'
                                    : 'bg-slate-100 text-slate-500 dark:bg-slate-800'
                              )}
                            >
                              {ms.year} • {ms.status}
                            </span>
                          </div>
                          <h5 className="text-lg font-black dark:text-white">{ms.title}</h5>
                          <p className="text-slate-500 dark:text-slate-400 text-sm leading-relaxed">
                            {ms.description}
                          </p>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            </motion.div>
          ) : (
            <div className="glass p-16 rounded-[2.5rem] text-center">
              <Layers className="w-16 h-16 text-slate-200 dark:text-slate-800 mx-auto mb-4" />
              <h3 className="text-xl font-bold text-slate-400">Select a technology to start planning</h3>
            </div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}

function clsx(...classes: any[]) {
  return classes.filter(Boolean).join(' ');
}

